apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-microservice
  namespace: development
spec:
  provider: vault
  parameters:
    vaultAddress: "http://<VAULT_INTERNAL_LB_ADDRESS>:8200"
    roleName: "development-microservice"
    objects: |
      - objectName: "microservice-secret"
        secretPath: "secret/data/microservice"
        secretKey: "value"
  secretObjects:
    - secretName: microservice-vault-secret
      type: Opaque
      data:
        - objectName: "microservice-secret"
          key: value
