apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: development
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes-development
  kubernetes:
    role: development-microservice
    serviceAccount: microservice
    audiences:
      - vault
