apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: development
spec:
  address: "http://<VAULT_INTERNAL_LB_ADDRESS>:8200"
  skipTLSVerify: true
