apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: microservice-secret
  namespace: development
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: microservice
  refreshAfter: 30s
  destination:
    name: microservice-vault-secret
    create: true
