controller:
  additionalPlugins:
    - hashicorp-vault-plugin
    - docker-workflow
    - timestamper

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi

  JCasC:
    configScripts:
      vault-credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - vaultKubernetesCredential:
                      scope: GLOBAL
                      id: "vault-k8s-auth"
                      description: "Kubernetes auth contra Vault (mount kubernetes-jenkins)"
                      mountPath: "kubernetes-jenkins"
                      role: "jenkins-microservice"

persistence:
  enabled: true
  size: 8Gi

agent:
  enabled: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
