apiVersion: v1
kind: Service
metadata:
  name: vault-internal-lb
  namespace: vault
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "<PRIVATE_SUBNET_ID_1>,<PRIVATE_SUBNET_ID_2>"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    component: server
  ports:
    - name: api
      port: 8200
      targetPort: 8200
