apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: development
  labels:
    app: microservice
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "<PUBLIC_SUBNET_ID_1>,<PUBLIC_SUBNET_ID_2>"
spec:
  type: LoadBalancer
  selector:
    app: microservice
  ports:
    - name: http
      port: 80
      targetPort: http
