server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized

app:
  vault:
    secret-env-var: ${VAULT_SECRET_ENV_VAR:VAULT_SECRET}
  config:
    message: ${APP_CONFIG_MESSAGE:configuracion-local-por-defecto}
